@URL=http://localhost/Projeto/api

### Obter todos os registros da tabela produto_categoria
GET {{URL}}/proCat/get.php

### Criar um produto_categoria
POST {{URL}}/proCat/create.php
Content-Type: application/json

{
  "id_produto": "2",
  "id_categoria": "2"
}