@URL=http://localhost/Projeto/api

### Obter todos as categorias
GET {{URL}}/categoria/get.php

### Atualizar categoria
POST {{URL}}/categoria/update.php?id=3
Content-Type: application/json

{
  "nome": "Categoria simples"
}

### Criar uma categoria
POST {{URL}}/categoria/create.php
Content-Type: application/json

{
  "nome": "Categoria basica II"
}


### Deletar uma categoria
GET {{URL}}/categoria/delete.php?id=2