@URL=http://localhost/Projeto/api

### Obter todos os usuários
GET {{URL}}/usuario/get.php

### Atualizar usuário
POST {{URL}}/usuario/update.php?id=3
Content-Type: application/json

{
  "nome": "Maria  II",
  "email": "lind@a.com",
  "nascimento": "2000-05-05"
}

### Criar um usuário
POST {{URL}}/usuario/create.php
Content-Type: application/json

{
  "nome": "Maria",
  "email": "lind@a.com",
  "nascimento": "2000-05-05",
  "senha": "1234"
}


### Deletar um usuário
GET {{URL}}/usuario/delete.php?id=2